name: Manual Trigger - Modify & Webhook

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  auto-update-and-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp file
        run: |
          echo "Last updated at $(date)" > last-updated.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last-updated.txt
          git commit -m "Auto update timestamp"
          git push

      - name: Trigger Webhook
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ufdJaXXohQmK5Xul5fJgjFjq6ZZv/azby8BcNvM
