name: Manual Trigger - Modify & Webhook

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI

# Add this permissions block
permissions:
  contents: write

jobs:
  auto-update-and-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp file
        run: |
          echo "Last updated at $(date)" > last-updated.txt

      - name: Commit changes and push using GITHUB_TOKEN
        run: |
          git config user.name "vamsi-convertedgetech"
          git config user.email "vamsib@convertedgetech.com"
          git add last-updated.txt
          git commit -m "Auto update timestamp"
          git push

      - name: Trigger Webhook
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_ufdJaXXohQmK5Xul5fJgjFjq6ZZv/azby8BcNvM
